### ISSUE TITLE
Refactor CI to be run with `uds run` instead of `make`

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/uds-capability-rook-ceph#79]
The [UDS Runner](https://github.com/defenseunicorns/uds-cli/blob/main/docs/runner.md) should be usable for our CI at this point, and simplify things rather than some of the messy makefile creations.

We should switch off of make and turn the CI/dev targets into uds run commands.

**Comment by JoeHCQ1** [comment]
Status: near the end of this, trying to get a pipeline run to pass, currently failing the upgrade test due to just how old the last release is (it depends on the outdated zarf release url).

**Comment by JoeHCQ1** [comment]
This is being worked in order to prep the rook/ceph package for use in the client environment should it become expedient.
