### ISSUE TITLE
TODO: Switch back to IB once 1.12.9 is published -https://repo1.dso.mil/dsop/rook/ceph/-/issues/118

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/uds-capability-rook-ceph#80]
TODO: Switch back to IB once 1.12.9 is published -https://repo1.dso.mil/dsop/rook/ceph/-/issues/118

_Originally posted by @mjnagel in https://github.com/defenseunicorns/uds-capability-rook-ceph/pull/78#discussion_r1412629471_

**Comment by mjnagel** [comment]
Needs changes in two files:
- `values/operator-values.yaml`
- `rook-ceph/zarf.yaml`
